name: palettenerf
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - ninja
  - trimesh
  - opencv
  - tensorboardX
  - numpy 
  - pandas
  - tqdm
  - matplotlib
  - rich
  - packaging
  - scipy 
  - pip
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda=11.6
  - pip:
    - cvxopt
    - cython
    - imageio
    - lpips
    - torch-ema
    - PyMCubes
    - pysdf
    - scikit-image
    - scikit-learn
    - dearpygui
    - kornia
    - imageio-ffmpeg
    # - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
